#!/usr/bin/env python3
import os
import sys

# Add the local directory to sys.path to find the kicad_skill package
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kicad_skill.main import main

if __name__ == '__main__':
    main()
